name: questionaire service CD for dev

on:
  watch:
    types: [started]

jobs:
  deploy:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["k8s/*.yaml"]'
      env:
        DOCKER_TAG: ${{ steps.package-version.outputs.current-version}}
        INSTANCE_NUM: 1
    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f ./k8s -n dev

