name: questionaire service CD for uat

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/uat-release') == true
    steps:
    - uses: actions/checkout@v2
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["k8s/*.yaml"]'
      env:
        DOCKER_TAG: ${{ steps.package-version.outputs.current-version}}
        INSTANCE_NUM: 1
        DB_NAME: uat-questionaire
    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f ./k8s -n uat

